env:
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  project: ["./tsconfig.json"]
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  "@typescript-eslint/no-explicit-any":
    - error
