---
version: "2.4"
services:

  builder:
    build:
      context: ./docker/builder/

    ports:
      - 3000:3000

    volumes:
      - .:/project

      # Keep node_modules only inside a volume (for decluttering and performance)
      - nodemodules_builder:/project/node_modules

      # Sync time with host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    working_dir: /project

    command: ./scripts/build.sh --serve


  hass:
    image: homeassistant/home-assistant:beta

    environment:
      - SWIPE_NAVIGATION_JS_URL=http://builder:3000/swipe-navigation.js

    ports:
      - 8123:8123

    volumes:
      - .hass/hass-init.sh:/etc/cont-init.d/hass-init.sh:ro
      - .hass/config/configuration.yaml:/config/configuration.yaml:ro
      - .hass/config/dashboards.yaml:/config/dashboards.yaml:ro
      - .hass/config/ui-lovelace.yaml:/config/ui-lovelace.yaml:ro
      - .hass/config/dashboards/:/config/dashboards
      - .hass/config/packages:/config/packages
      - .hass/config/www/touchpoints-visualizer.js:/config/www/touchpoints-visualizer.js:ro

      # Sync time with host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


  tester:
    build:
      context: ./docker/builder/

    environment:
      - CI
      - HOMEASSISTANT_URL=http://hass:8123
      - SWIPE_NAVIGATION_JS_URL=http://builder:3000/swipe-navigation.js

    volumes:
      - .:/project

      # Keep node_modules only inside a volume (for decluttering and performance)
      - nodemodules_tester:/project/node_modules

      # Sync time with host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    working_dir: /project

    depends_on:
      - builder
      - hass

    profiles:
      - tests

    command: ./scripts/run-playwright.sh


volumes:
  nodemodules_builder:
  nodemodules_tester:
