# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages/


lovelace: !include dashboards.yaml

frontend:
  themes: !include_dir_merge_named themes
