# This file overrides the main docker-compose.yml

version: '2.4'
services:
  builder:

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
