name: Build on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    - name: Set version number
      run: |
        case ${GITHUB_REF} in
          refs/heads/*)
            GITHUB_REF_CLEAN=${GITHUB_REF#refs/heads/}
              ;;
          refs/tags/*)
            GITHUB_REF_CLEAN=${GITHUB_REF#refs/tags/}
            ;;
        esac
        sed -i "s|VERSION_PLACEHOLDER|${GITHUB_REF_CLEAN}|g" src/swipe-navigation.ts

    - name: Build project
      run: scripts/build.sh

    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/swipe-navigation.js
