name: Build on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set version number
      run: |
        case ${GITHUB_REF} in
          refs/heads/*)
            GITHUB_REF_CLEAN=${GITHUB_REF#refs/heads/}
              ;;
          refs/tags/*)
            GITHUB_REF_CLEAN=${GITHUB_REF#refs/tags/}
            ;;
        esac
        sed -i "s|VERSION_PLACEHOLDER|${GITHUB_REF_CLEAN}|g" src/swipe-navigation.ts

    - name: Build project
      run: scripts/build.sh

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/swipe-navigation.js
        asset_name: swipe-navigation.js
        asset_content_type: text/javascript
