name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

      # Connect to the runner with ssh for debugging
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Spin up containers
      run: docker-compose --profile tests up --exit-code-from tester

    - name: Stop containers
      if: always()
      run: docker-compose down

    - name: Get logs in case of failure
      if: failure()
      run: docker-compose logs --no-color > logs.txt

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: docker-logs.txt
        path: logs.txt
        retention-days: 7

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        if-no-files-found: ignore
        retention-days: 7

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
