name: Playwright Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: "0 0 1 * *" # Every first day of the month, so we test with the last beta release

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

      # Connect to the runner with ssh for debugging
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Spin up containers
      run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from tester

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.yml -f docker-compose.test.yml down

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        if-no-files-found: ignore
        retention-days: 7

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
